import "./globals.css";
import classNames from "classnames";
import { Inter } from "next/font/google";
import { Header } from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const bodyClassName = classNames(
    inter.className,
    "my-8 my-[16px] lg:mx-[60px]"
  );
  return (
    <html lang="en">
      <body className={bodyClassName}>
        <Header />
        {children}
      </body>
    </html>
  );
}
